"""empty message

Revision ID: 32bf8b2a38dd
Revises: 
Create Date: 2021-12-03 18:39:14.368293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bf8b2a38dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Unicode(length=128), nullable=False),
    sa.Column('firstname', sa.Unicode(length=128), nullable=False),
    sa.Column('lastname', sa.Unicode(length=128), nullable=False),
    sa.Column('password', sa.Unicode(length=128), nullable=True),
    sa.Column('dateofbirth', sa.Date(), nullable=True),
    sa.Column('reports', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('content_filter', sa.Boolean(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blacklist',
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member'], ['User.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['User.id'], ),
    sa.PrimaryKeyConstraint('owner', 'member')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    op.drop_table('User')
    # ### end Alembic commands ###
