name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test docker deployment
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: (arbitrarily) wait for all services to be up
      run: sleep 120
    - name: Shutdown docker
      if: always()
      run: docker-compose -f "docker-compose.yml" down